#!/usr/bin/env node
// KNS Picture House - build script
// Reads data/movies.json (the database), emits site/data.js so the site works
// from file:// and any static host without CORS issues.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const db = JSON.parse(readFileSync(join(root, 'data', 'movies.json'), 'utf8'));

// Inline posters as data URIs so the site ships as flat root files.
const movies = db.movies.map((m) => {
  if (m.poster) {
    const p = join(root, 'site', m.poster);
    if (existsSync(p)) {
      const b64 = readFileSync(p).toString('base64');
      return { ...m, poster: 'data:image/jpeg;base64,' + b64 };
    }
  }
  return m;
});

const payload = {
  generated_at: new Date().toISOString(),
  club: db.club,
  source: db.source,
  movies,
};

// Split output so no single file exceeds ~550KB: GitHub's web editor
// (used for commits without git push access) rejects very large pastes.
// data.js carries metadata; posters-{a,b,c}.js carry base64 posters and are
// merged back onto KNS_DATA by an inline snippet in index.html.
const noPosters = { ...payload, movies: payload.movies.map((m) => ({ ...m, poster: m.poster.startsWith('data:') ? '' : m.poster })) };
writeFileSync(
  join(root, 'site', 'data.js'),
  '// GENERATED by scripts/build.mjs - do not edit by hand\n' +
  'window.KNS_DATA = ' + JSON.stringify(noPosters, null, 2) + ';\n'
);
const posters = {};
for (const m of payload.movies) if (m.poster.startsWith('data:')) posters[m.id] = m.poster;
const ids = Object.keys(posters);
const CHUNKS = 3;
for (let i = 0; i < CHUNKS; i++) {
  const part = {};
  ids.forEach((id, j) => { if (j % CHUNKS === i) part[id] = posters[id]; });
  writeFileSync(
    join(root, 'site', `posters-${'abc'[i]}.js`),
    'window.KNS_POSTERS = window.KNS_POSTERS || {};\nObject.assign(window.KNS_POSTERS, ' + JSON.stringify(part) + ');\n'
  );
}
console.log(`Built site/data.js + ${CHUNKS} poster chunks with ${db.movies.length} films.`);
